# Generated by Django 6.0.2 on 2026-04-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilisateur_groups_utilisateur_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
