# Generated by Django 6.0.2 on 2026-04-15 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_utilisateur_salle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('taux_commission_defaut', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
