# Generated by Django 6.0.2 on 2026-04-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Admin'), ('personnel', 'Personnel')], default='personnel', max_length=20),
        ),
    ]
