# Generated by Django 6.0.2 on 2026-04-15 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0001_initial'),
        ('users', '0010_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleFournisseur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taux_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('transfere', 'Transféré')], default='actif', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='users.fournisseur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='salles.salle')),
            ],
            options={
                'unique_together': {('salle', 'fournisseur', 'statut')},
            },
        ),
    ]
