# Generated by Django 6.0.2 on 2026-03-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignevente',
            options={'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vente', 'verbose_name_plural': 'Ventes'},
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix',
            new_name='prix_unitaire',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='stock_min',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='date',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='est_paye',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='montant_total',
        ),
        migrations.AddField(
            model_name='lignevente',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.CharField(choices=[('complement', 'Complément alimentaire'), ('pre_workout', 'Pre-Workout'), ('dose', 'Dose'), ('autre', 'Autre')], default='complement', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='prix_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vente',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
    ]
