# Generated by Django 6.0.2 on 2026-04-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_make_salle_required'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='salles.salle'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='salles.salle'),
        ),
    ]
