# Generated by Django 6.0.2 on 2026-04-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_alter_produit_salle_alter_vente_salle'),
        ('salles', '0002_sallefournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='salles.salle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vente',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='salles.salle'),
            preserve_default=False,
        ),
    ]
