# Generated by Django 6.0.2 on 2026-03-04 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('places_total', models.IntegerField(default=5)),
                ('places_disponibles', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Séance',
                'verbose_name_plural': 'Séances',
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('date', 'heure_debut')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_appareil', models.CharField(choices=[('i-motion', 'i-Motion'), ('i-model', 'i-Model')], max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('présent', 'Présent'), ('absent', 'Absent'), ('annulé', 'Annulé')], default='en_attente', max_length=15)),
                ('est_rattrapage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='clients.abonnement')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_creees', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='seances.seance')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
