# Generated by Django 6.0.2 on 2026-03-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('present', 'Présent'), ('absent', 'Absent'), ('annule', 'Annulé')], default='en_attente', max_length=15),
        ),
    ]
