# Generated by Django 6.0.2 on 2026-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0003_add_taille_gilet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='taille_gilet',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], default=None, max_length=3, null=True),
        ),
    ]
