# Generated by Django 6.0.2 on 2026-04-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seances', '0005_alter_reservation_abonnement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='taille_gilet',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='seance',
            name='places_disponibles',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='seance',
            name='places_total',
            field=models.IntegerField(default=3),
        ),
    ]
