# Generated by Django 6.0.2 on 2026-04-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0001_initial'),
        ('seances', '0009_make_salle_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='salles.salle'),
        ),
    ]
