# Generated by Django 6.0.2 on 2026-04-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salles', '0002_sallefournisseur'),
        ('seances', '0010_alter_seance_salle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='salles.salle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seance',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='salles.salle'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seance',
            unique_together={('date', 'heure_debut', 'salle')},
        ),
    ]
