# Generated by Django 6.0.2 on 2026-03-04 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_action', models.CharField(choices=[('CLIENT', 'Client'), ('ABONNEMENT', 'Abonnement'), ('RESERVATION', 'Réservation'), ('VENTE', 'Vente'), ('AUTH', 'Authentification')], max_length=20)),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('PAIEMENT', 'Paiement'), ('ACTIVATION', 'Activation'), ('DESACTIVATION', 'Désactivation')], max_length=20)),
                ('entite_concernee', models.CharField(max_length=50)),
                ('entite_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique',
                'verbose_name_plural': 'Historiques',
                'ordering': ['-created_at'],
            },
        ),
    ]
