# Generated by Django 6.0.2 on 2026-03-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historique',
            old_name='utilisateur',
            new_name='personnel',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='entite_concernee',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='entite_id',
        ),
        migrations.RemoveField(
            model_name='historique',
            name='type_action',
        ),
        migrations.AddField(
            model_name='historique',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='historique',
            name='action',
            field=models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('creer_client', 'Créer client'), ('creer_abonnement', 'Créer abonnement'), ('creer_reservation', 'Créer réservation'), ('marquer_present', 'Marquer présent'), ('creer_vente', 'Créer vente')], max_length=30),
        ),
    ]
