# Generated by Django 6.0.2 on 2026-04-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0006_alter_historique_salle'),
        ('salles', '0002_sallefournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='salles.salle'),
            preserve_default=False,
        ),
    ]
