# Generated by Django 6.0.2 on 2026-03-04 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('telephone_1', models.CharField(max_length=20)),
                ('telephone_2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/')),
                ('essai_fait', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('essai', 'Séance Essai'), ('normale', 'Séance Normale'), ('pack10', 'Pack 10'), ('pack20', 'Pack 20')], max_length=10)),
                ('prix_paye', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mode_paiement', models.CharField(blank=True, choices=[('cash', 'Cash'), ('tpe', 'TPE')], default='', max_length=10)),
                ('est_paye', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('seances_total', models.IntegerField(default=0)),
                ('seances_restantes', models.IntegerField(default=0)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_derniere_seance', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En Attente'), ('actif', 'Actif'), ('expiré', 'Expiré'), ('terminé', 'Terminé')], default='en_attente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='clients.client')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
    ]
