# Generated by Django 6.0.2 on 2026-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='reduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Réduction en pourcentage (0-100)', max_digits=5),
        ),
    ]
