# Generated by Django 6.0.2 on 2026-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_abonnement_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('essai', 'Essai'), ('normale', 'Normale'), ('pack10', 'Pack 10'), ('pack20', 'Pack 20')], max_length=10),
        ),
    ]
