# Generated by Django 6.0.2 on 2026-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_abonnement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='type',
            field=models.CharField(choices=[('essai', 'Essai'), ('unique', 'Unique'), ('pack5', 'Pack 5'), ('pack10', 'Pack 10'), ('pack20', 'Pack 20'), ('pack30', 'Pack 30')], max_length=10),
        ),
    ]
