# Generated by Django 6.0.2 on 2026-03-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_abonnement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='clients.client'),
        ),
    ]
