# Generated by Django 6.0.2 on 2026-04-08 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_make_salle_required_and_client_constraints'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='salles.salle'),
        ),
        migrations.AlterField(
            model_name='client',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='salles.salle'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='salles.salle'),
        ),
    ]
