# Generated by Django 6.0.2 on 2026-04-15 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_alter_abonnement_salle_alter_client_salle_and_more'),
        ('salles', '0002_sallefournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='salles.salle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='salles.salle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pack',
            name='salle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='salles.salle'),
            preserve_default=False,
        ),
    ]
